name: go1.17

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    # Monthly test. Runs at 19:30 UTC (AM 04:30 JST) on day-of-month 1
    - cron: '30 19 1 * *'

jobs:
  go1-16:
    name: Run on Go v1.17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run on Go 1.17
        run: docker-compose up v1_17